version: '3'
services:
  db:
    container_name: fullstack-job-db
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: fullstack-job
  redis:
    container_name: fullstack-job-redis
    image: redis:latest
    ports:
      - '6379:6379'
  api:
    container_name: fullstack-job-api
    build: ./api
    ports:
      - '5000:5000'
    volumes:
      - ./api:/app
    depends_on:
      - db
      - redis
    command: ["./wait-for-it.sh", "db:5432", "--", "flask", "run", "--host", "0.0.0.0", "--debug"]
  # frontend:
  #   container_name: fullstack-job-frontend
  #   build:
  #     context: ./frontend
  #   ports:
  #     - '5173:5173'
  #   volumes:
  #     - type: bind
  #       source: ./frontend
  #       target: /app
  #     - /app/node_modules
  #   depends_on:
  #     - api
  